services:
  mongo:
    image: mongo:latest
    container_name: db-bot
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
    volumes:
      - ./data/mongo:/data/db
